/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_papenhagen_jniplay_MainApp */

#ifndef _Included_eu_papenhagen_jniplay_MainApp
#define _Included_eu_papenhagen_jniplay_MainApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_papenhagen_jniplay_MainApp
 * Method:    output
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_papenhagen_jniplay_MainApp_output
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
